// Code generated by protoc-gen-go. DO NOT EDIT.
// source: virtualnetwork.proto

package network

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VirtualNetworkType int32

const (
	VirtualNetworkType_NAT               VirtualNetworkType = 0
	VirtualNetworkType_Transparent       VirtualNetworkType = 1
	VirtualNetworkType_L2Bridge          VirtualNetworkType = 2
	VirtualNetworkType_L2Tunnel          VirtualNetworkType = 3
	VirtualNetworkType_ICS               VirtualNetworkType = 4
	VirtualNetworkType_Private           VirtualNetworkType = 5
	VirtualNetworkType_Overlay           VirtualNetworkType = 6
	VirtualNetworkType_Internal          VirtualNetworkType = 7
	VirtualNetworkType_Mirrored          VirtualNetworkType = 8
	VirtualNetworkType_OpenVSwitchBridge VirtualNetworkType = 9
)

var VirtualNetworkType_name = map[int32]string{
	0: "NAT",
	1: "Transparent",
	2: "L2Bridge",
	3: "L2Tunnel",
	4: "ICS",
	5: "Private",
	6: "Overlay",
	7: "Internal",
	8: "Mirrored",
	9: "OpenVSwitchBridge",
}

var VirtualNetworkType_value = map[string]int32{
	"NAT":               0,
	"Transparent":       1,
	"L2Bridge":          2,
	"L2Tunnel":          3,
	"ICS":               4,
	"Private":           5,
	"Overlay":           6,
	"Internal":          7,
	"Mirrored":          8,
	"OpenVSwitchBridge": 9,
}

func (x VirtualNetworkType) String() string {
	return proto.EnumName(VirtualNetworkType_name, int32(x))
}

func (VirtualNetworkType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4ae143cdfc584285, []int{0}
}

type VirtualNetworkRequest struct {
	VirtualNetworks      []*VirtualNetwork `protobuf:"bytes,1,rep,name=VirtualNetworks,proto3" json:"VirtualNetworks,omitempty"`
	OperationType        common.Operation  `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VirtualNetworkRequest) Reset()         { *m = VirtualNetworkRequest{} }
func (m *VirtualNetworkRequest) String() string { return proto.CompactTextString(m) }
func (*VirtualNetworkRequest) ProtoMessage()    {}
func (*VirtualNetworkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae143cdfc584285, []int{0}
}

func (m *VirtualNetworkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualNetworkRequest.Unmarshal(m, b)
}
func (m *VirtualNetworkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualNetworkRequest.Marshal(b, m, deterministic)
}
func (m *VirtualNetworkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualNetworkRequest.Merge(m, src)
}
func (m *VirtualNetworkRequest) XXX_Size() int {
	return xxx_messageInfo_VirtualNetworkRequest.Size(m)
}
func (m *VirtualNetworkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualNetworkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualNetworkRequest proto.InternalMessageInfo

func (m *VirtualNetworkRequest) GetVirtualNetworks() []*VirtualNetwork {
	if m != nil {
		return m.VirtualNetworks
	}
	return nil
}

func (m *VirtualNetworkRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type VirtualNetworkResponse struct {
	VirtualNetworks      []*VirtualNetwork   `protobuf:"bytes,1,rep,name=VirtualNetworks,proto3" json:"VirtualNetworks,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *VirtualNetworkResponse) Reset()         { *m = VirtualNetworkResponse{} }
func (m *VirtualNetworkResponse) String() string { return proto.CompactTextString(m) }
func (*VirtualNetworkResponse) ProtoMessage()    {}
func (*VirtualNetworkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae143cdfc584285, []int{1}
}

func (m *VirtualNetworkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualNetworkResponse.Unmarshal(m, b)
}
func (m *VirtualNetworkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualNetworkResponse.Marshal(b, m, deterministic)
}
func (m *VirtualNetworkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualNetworkResponse.Merge(m, src)
}
func (m *VirtualNetworkResponse) XXX_Size() int {
	return xxx_messageInfo_VirtualNetworkResponse.Size(m)
}
func (m *VirtualNetworkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualNetworkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualNetworkResponse proto.InternalMessageInfo

func (m *VirtualNetworkResponse) GetVirtualNetworks() []*VirtualNetwork {
	if m != nil {
		return m.VirtualNetworks
	}
	return nil
}

func (m *VirtualNetworkResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *VirtualNetworkResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type VirtualNetwork struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string             `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Ipams                []*Ipam            `protobuf:"bytes,3,rep,name=ipams,proto3" json:"ipams,omitempty"`
	Dns                  *common.Dns        `protobuf:"bytes,4,opt,name=dns,proto3" json:"dns,omitempty"`
	Type                 VirtualNetworkType `protobuf:"varint,5,opt,name=type,proto3,enum=moc.nodeagent.network.VirtualNetworkType" json:"type,omitempty"`
	MacPool              *MacPool           `protobuf:"bytes,6,opt,name=macPool,proto3" json:"macPool,omitempty"`
	Status               *common.Status     `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Entity               *common.Entity     `protobuf:"bytes,9,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *VirtualNetwork) Reset()         { *m = VirtualNetwork{} }
func (m *VirtualNetwork) String() string { return proto.CompactTextString(m) }
func (*VirtualNetwork) ProtoMessage()    {}
func (*VirtualNetwork) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae143cdfc584285, []int{2}
}

func (m *VirtualNetwork) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualNetwork.Unmarshal(m, b)
}
func (m *VirtualNetwork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualNetwork.Marshal(b, m, deterministic)
}
func (m *VirtualNetwork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualNetwork.Merge(m, src)
}
func (m *VirtualNetwork) XXX_Size() int {
	return xxx_messageInfo_VirtualNetwork.Size(m)
}
func (m *VirtualNetwork) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualNetwork.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualNetwork proto.InternalMessageInfo

func (m *VirtualNetwork) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualNetwork) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VirtualNetwork) GetIpams() []*Ipam {
	if m != nil {
		return m.Ipams
	}
	return nil
}

func (m *VirtualNetwork) GetDns() *common.Dns {
	if m != nil {
		return m.Dns
	}
	return nil
}

func (m *VirtualNetwork) GetType() VirtualNetworkType {
	if m != nil {
		return m.Type
	}
	return VirtualNetworkType_NAT
}

func (m *VirtualNetwork) GetMacPool() *MacPool {
	if m != nil {
		return m.MacPool
	}
	return nil
}

func (m *VirtualNetwork) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *VirtualNetwork) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type MacRange struct {
	StartMacAddress      string   `protobuf:"bytes,1,opt,name=startMacAddress,proto3" json:"startMacAddress,omitempty"`
	EndMacAddress        string   `protobuf:"bytes,2,opt,name=endMacAddress,proto3" json:"endMacAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MacRange) Reset()         { *m = MacRange{} }
func (m *MacRange) String() string { return proto.CompactTextString(m) }
func (*MacRange) ProtoMessage()    {}
func (*MacRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae143cdfc584285, []int{3}
}

func (m *MacRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MacRange.Unmarshal(m, b)
}
func (m *MacRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MacRange.Marshal(b, m, deterministic)
}
func (m *MacRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MacRange.Merge(m, src)
}
func (m *MacRange) XXX_Size() int {
	return xxx_messageInfo_MacRange.Size(m)
}
func (m *MacRange) XXX_DiscardUnknown() {
	xxx_messageInfo_MacRange.DiscardUnknown(m)
}

var xxx_messageInfo_MacRange proto.InternalMessageInfo

func (m *MacRange) GetStartMacAddress() string {
	if m != nil {
		return m.StartMacAddress
	}
	return ""
}

func (m *MacRange) GetEndMacAddress() string {
	if m != nil {
		return m.EndMacAddress
	}
	return ""
}

type MacPool struct {
	Ranges               []*MacRange `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MacPool) Reset()         { *m = MacPool{} }
func (m *MacPool) String() string { return proto.CompactTextString(m) }
func (*MacPool) ProtoMessage()    {}
func (*MacPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae143cdfc584285, []int{4}
}

func (m *MacPool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MacPool.Unmarshal(m, b)
}
func (m *MacPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MacPool.Marshal(b, m, deterministic)
}
func (m *MacPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MacPool.Merge(m, src)
}
func (m *MacPool) XXX_Size() int {
	return xxx_messageInfo_MacPool.Size(m)
}
func (m *MacPool) XXX_DiscardUnknown() {
	xxx_messageInfo_MacPool.DiscardUnknown(m)
}

var xxx_messageInfo_MacPool proto.InternalMessageInfo

func (m *MacPool) GetRanges() []*MacRange {
	if m != nil {
		return m.Ranges
	}
	return nil
}

type Subnet struct {
	Name                 string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string                    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Cidr                 string                    `protobuf:"bytes,3,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Routes               []*Route                  `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	Allocation           common.IPAllocationMethod `protobuf:"varint,5,opt,name=allocation,proto3,enum=moc.IPAllocationMethod" json:"allocation,omitempty"`
	Vlan                 uint32                    `protobuf:"varint,6,opt,name=vlan,proto3" json:"vlan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Subnet) Reset()         { *m = Subnet{} }
func (m *Subnet) String() string { return proto.CompactTextString(m) }
func (*Subnet) ProtoMessage()    {}
func (*Subnet) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae143cdfc584285, []int{5}
}

func (m *Subnet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subnet.Unmarshal(m, b)
}
func (m *Subnet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subnet.Marshal(b, m, deterministic)
}
func (m *Subnet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subnet.Merge(m, src)
}
func (m *Subnet) XXX_Size() int {
	return xxx_messageInfo_Subnet.Size(m)
}
func (m *Subnet) XXX_DiscardUnknown() {
	xxx_messageInfo_Subnet.DiscardUnknown(m)
}

var xxx_messageInfo_Subnet proto.InternalMessageInfo

func (m *Subnet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Subnet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Subnet) GetCidr() string {
	if m != nil {
		return m.Cidr
	}
	return ""
}

func (m *Subnet) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func (m *Subnet) GetAllocation() common.IPAllocationMethod {
	if m != nil {
		return m.Allocation
	}
	return common.IPAllocationMethod_Invalid
}

func (m *Subnet) GetVlan() uint32 {
	if m != nil {
		return m.Vlan
	}
	return 0
}

type Ipam struct {
	Type                 string    `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Subnets              []*Subnet `protobuf:"bytes,2,rep,name=subnets,proto3" json:"subnets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Ipam) Reset()         { *m = Ipam{} }
func (m *Ipam) String() string { return proto.CompactTextString(m) }
func (*Ipam) ProtoMessage()    {}
func (*Ipam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae143cdfc584285, []int{6}
}

func (m *Ipam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ipam.Unmarshal(m, b)
}
func (m *Ipam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ipam.Marshal(b, m, deterministic)
}
func (m *Ipam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ipam.Merge(m, src)
}
func (m *Ipam) XXX_Size() int {
	return xxx_messageInfo_Ipam.Size(m)
}
func (m *Ipam) XXX_DiscardUnknown() {
	xxx_messageInfo_Ipam.DiscardUnknown(m)
}

var xxx_messageInfo_Ipam proto.InternalMessageInfo

func (m *Ipam) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Ipam) GetSubnets() []*Subnet {
	if m != nil {
		return m.Subnets
	}
	return nil
}

type Route struct {
	Nexthop              string   `protobuf:"bytes,1,opt,name=nexthop,proto3" json:"nexthop,omitempty"`
	Destinationprefix    string   `protobuf:"bytes,2,opt,name=destinationprefix,proto3" json:"destinationprefix,omitempty"`
	Metric               uint32   `protobuf:"varint,3,opt,name=metric,proto3" json:"metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae143cdfc584285, []int{7}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetNexthop() string {
	if m != nil {
		return m.Nexthop
	}
	return ""
}

func (m *Route) GetDestinationprefix() string {
	if m != nil {
		return m.Destinationprefix
	}
	return ""
}

func (m *Route) GetMetric() uint32 {
	if m != nil {
		return m.Metric
	}
	return 0
}

func init() {
	proto.RegisterEnum("moc.nodeagent.network.VirtualNetworkType", VirtualNetworkType_name, VirtualNetworkType_value)
	proto.RegisterType((*VirtualNetworkRequest)(nil), "moc.nodeagent.network.VirtualNetworkRequest")
	proto.RegisterType((*VirtualNetworkResponse)(nil), "moc.nodeagent.network.VirtualNetworkResponse")
	proto.RegisterType((*VirtualNetwork)(nil), "moc.nodeagent.network.VirtualNetwork")
	proto.RegisterType((*MacRange)(nil), "moc.nodeagent.network.MacRange")
	proto.RegisterType((*MacPool)(nil), "moc.nodeagent.network.MacPool")
	proto.RegisterType((*Subnet)(nil), "moc.nodeagent.network.Subnet")
	proto.RegisterType((*Ipam)(nil), "moc.nodeagent.network.Ipam")
	proto.RegisterType((*Route)(nil), "moc.nodeagent.network.Route")
}

func init() { proto.RegisterFile("virtualnetwork.proto", fileDescriptor_4ae143cdfc584285) }

var fileDescriptor_4ae143cdfc584285 = []byte{
	// 828 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xde, 0xf1, 0xcf, 0xd8, 0x29, 0x6f, 0x92, 0x49, 0xef, 0x26, 0x0c, 0x5e, 0x58, 0x22, 0x03,
	0x52, 0x40, 0xcb, 0x18, 0xcc, 0x4a, 0xe1, 0xc2, 0x21, 0x59, 0x22, 0x61, 0x84, 0x93, 0xa8, 0x1d,
	0xe5, 0xb0, 0xb7, 0xce, 0x4c, 0xc5, 0x1e, 0x65, 0xa6, 0x7b, 0xe8, 0xee, 0x71, 0x92, 0x97, 0x41,
	0xbc, 0x03, 0x8f, 0xc0, 0x85, 0x03, 0x0f, 0x85, 0xba, 0xa7, 0x1d, 0x6c, 0x07, 0x4b, 0x39, 0xec,
	0xad, 0xab, 0xea, 0xab, 0xaa, 0xaf, 0xbe, 0xae, 0xe9, 0x81, 0x97, 0xb3, 0x54, 0xea, 0x92, 0x65,
	0x1c, 0xf5, 0xad, 0x90, 0x37, 0x51, 0x21, 0x85, 0x16, 0x64, 0x37, 0x17, 0x71, 0xc4, 0x45, 0x82,
	0x6c, 0x82, 0x5c, 0x47, 0x2e, 0xd8, 0x7d, 0x3d, 0x11, 0x62, 0x92, 0x61, 0xdf, 0x82, 0xae, 0xca,
	0xeb, 0xfe, 0xad, 0x64, 0x45, 0x81, 0x52, 0x55, 0x69, 0xdd, 0x57, 0xab, 0x71, 0xcc, 0x0b, 0x7d,
	0xef, 0x82, 0xcf, 0x63, 0x91, 0xe7, 0x82, 0x3b, 0xeb, 0x85, 0xab, 0xb9, 0xe4, 0x24, 0x5c, 0xe8,
	0xf4, 0x3a, 0x8d, 0x99, 0x4e, 0xe7, 0xbe, 0xde, 0xef, 0x1e, 0xec, 0x5e, 0x56, 0x1c, 0x4f, 0xab,
	0x14, 0x8a, 0xbf, 0x95, 0xa8, 0x34, 0x39, 0x83, 0xed, 0xe5, 0x80, 0x0a, 0xbd, 0xfd, 0xfa, 0x41,
	0x67, 0xf0, 0x65, 0xf4, 0xbf, 0xf4, 0xa3, 0x95, 0x32, 0xab, 0xd9, 0xe4, 0x2d, 0x6c, 0x9e, 0x15,
	0x28, 0x6d, 0xf7, 0x8b, 0xfb, 0x02, 0xc3, 0xda, 0xbe, 0x77, 0xb0, 0x35, 0xd8, 0xb2, 0xe5, 0x1e,
	0x22, 0x74, 0x19, 0xd4, 0xfb, 0xd3, 0x83, 0xbd, 0x55, 0x82, 0xaa, 0x10, 0x5c, 0xe1, 0x87, 0x67,
	0x38, 0x00, 0x9f, 0xa2, 0x2a, 0x33, 0x6d, 0xa9, 0x75, 0x06, 0xdd, 0xa8, 0x52, 0x3c, 0x9a, 0x2b,
	0x1e, 0x1d, 0x0b, 0x91, 0x5d, 0xb2, 0xac, 0x44, 0xea, 0x90, 0xe4, 0x25, 0x34, 0x4f, 0xa4, 0x14,
	0x32, 0xac, 0xef, 0x7b, 0x07, 0x1b, 0xb4, 0x32, 0x7a, 0xff, 0xd4, 0x60, 0x6b, 0xb9, 0x3a, 0x21,
	0xd0, 0xe0, 0x2c, 0xc7, 0xd0, 0xb3, 0x38, 0x7b, 0x26, 0x5b, 0x50, 0x4b, 0x13, 0xdb, 0x6c, 0x83,
	0xd6, 0xd2, 0x84, 0x7c, 0x07, 0xcd, 0xb4, 0x60, 0xb9, 0x0a, 0xeb, 0x76, 0x8e, 0x57, 0x6b, 0xe6,
	0x18, 0x16, 0x2c, 0xa7, 0x15, 0x92, 0x74, 0xa1, 0x9e, 0x70, 0x15, 0x36, 0x2c, 0xe1, 0xb6, 0x4d,
	0xf8, 0x89, 0x2b, 0x6a, 0x9c, 0xe4, 0x47, 0x68, 0x68, 0x23, 0x74, 0xd3, 0x0a, 0xfd, 0xd5, 0x93,
	0x54, 0x31, 0xa2, 0x53, 0x9b, 0x46, 0x7e, 0x80, 0x56, 0xce, 0xe2, 0x73, 0x21, 0xb2, 0xd0, 0xb7,
	0xe5, 0x5f, 0xaf, 0xa9, 0x30, 0xaa, 0x50, 0x74, 0x0e, 0x27, 0x9f, 0x83, 0xaf, 0x34, 0xd3, 0xa5,
	0x0a, 0xdb, 0x36, 0xb1, 0x63, 0x13, 0xc7, 0xd6, 0x45, 0x5d, 0xc8, 0x80, 0x90, 0xeb, 0x54, 0xdf,
	0x87, 0x1b, 0x0b, 0xa0, 0x13, 0xeb, 0xa2, 0x2e, 0xf4, 0x4b, 0xa3, 0xdd, 0x0a, 0xda, 0xbd, 0xf7,
	0xd0, 0x1e, 0xb1, 0x98, 0x32, 0x3e, 0x41, 0x72, 0x00, 0xdb, 0x4a, 0x33, 0xa9, 0x47, 0x2c, 0x3e,
	0x4a, 0x12, 0x89, 0x4a, 0x39, 0x49, 0x57, 0xdd, 0xe4, 0x0b, 0xd8, 0x44, 0x9e, 0x2c, 0xe0, 0x2a,
	0xa1, 0x97, 0x9d, 0xbd, 0x63, 0x68, 0x39, 0xfe, 0xe4, 0x10, 0x7c, 0x69, 0x7a, 0xcc, 0xf7, 0xe8,
	0xb3, 0xf5, 0xf3, 0x5a, 0x2e, 0xd4, 0xc1, 0x7b, 0x7f, 0x79, 0xe0, 0x8f, 0xcb, 0x2b, 0x8e, 0xfa,
	0x49, 0xd7, 0x4c, 0xa0, 0x11, 0xa7, 0xc9, 0x7c, 0x65, 0xec, 0x99, 0xbc, 0x05, 0x5f, 0x8a, 0x52,
	0xa3, 0xb9, 0x4a, 0xd3, 0xfb, 0x93, 0x35, 0xbd, 0xa9, 0x01, 0x51, 0x87, 0x25, 0x87, 0x00, 0x2c,
	0xcb, 0x44, 0xf5, 0x49, 0xbb, 0x7b, 0xfe, 0xc8, 0x66, 0x0e, 0xcf, 0x8f, 0x1e, 0x02, 0x23, 0xd4,
	0x53, 0x91, 0xd0, 0x05, 0xa8, 0xa1, 0x30, 0xcb, 0x18, 0xb7, 0x17, 0xbb, 0x49, 0xed, 0xb9, 0x37,
	0x86, 0x86, 0xd9, 0x2c, 0x13, 0xb3, 0x6b, 0xe3, 0x46, 0xb0, 0xbb, 0x70, 0x08, 0x2d, 0x65, 0x07,
	0x34, 0x2a, 0x1a, 0x7e, 0x9f, 0xae, 0xe1, 0x57, 0xc9, 0x40, 0xe7, 0xe8, 0xde, 0x04, 0x9a, 0x96,
	0x32, 0x09, 0xa1, 0xc5, 0xf1, 0x4e, 0x4f, 0x45, 0xe1, 0x0a, 0xcf, 0x4d, 0xf2, 0x06, 0x76, 0x12,
	0x54, 0x3a, 0xe5, 0x96, 0x5a, 0x21, 0xf1, 0x3a, 0xbd, 0x73, 0x6a, 0x3d, 0x0e, 0x90, 0x3d, 0xf0,
	0x73, 0xd4, 0x32, 0x8d, 0xad, 0x7c, 0x9b, 0xd4, 0x59, 0x5f, 0xff, 0xe1, 0x01, 0x79, 0xbc, 0xca,
	0xa4, 0x05, 0xf5, 0xd3, 0xa3, 0x8b, 0xe0, 0x19, 0xd9, 0x86, 0xce, 0x85, 0x64, 0x5c, 0x15, 0x4c,
	0x22, 0xd7, 0x81, 0x47, 0x9e, 0x43, 0xfb, 0xd7, 0xc1, 0xb1, 0x4c, 0x93, 0x09, 0x06, 0xb5, 0xca,
	0xba, 0x28, 0x39, 0xc7, 0x2c, 0xa8, 0x9b, 0xac, 0xe1, 0xbb, 0x71, 0xd0, 0x20, 0x1d, 0x68, 0x9d,
	0xcb, 0x74, 0xc6, 0x34, 0x06, 0x4d, 0x63, 0x9c, 0xcd, 0x50, 0x66, 0xec, 0x3e, 0xf0, 0x4d, 0xc2,
	0x90, 0x6b, 0x94, 0x9c, 0x65, 0x41, 0xcb, 0x58, 0xa3, 0xd4, 0x7c, 0xfa, 0x98, 0x04, 0x6d, 0xb2,
	0x0b, 0x3b, 0x67, 0x05, 0xf2, 0xcb, 0xf1, 0x6d, 0xaa, 0xe3, 0xa9, 0xeb, 0xb1, 0x31, 0xf8, 0xdb,
	0x83, 0x17, 0xcb, 0x14, 0x8f, 0x8c, 0x76, 0x64, 0x02, 0xfe, 0x90, 0xcf, 0xc4, 0x0d, 0x92, 0x37,
	0x4f, 0x7b, 0xb9, 0xaa, 0x27, 0xba, 0xfb, 0xcd, 0x13, 0xd1, 0xd5, 0x7b, 0xd9, 0x7b, 0x46, 0x7e,
	0x86, 0x9d, 0x77, 0x53, 0x8c, 0x6f, 0x4e, 0x17, 0x7e, 0x04, 0x64, 0xef, 0xd1, 0x2b, 0x77, 0x62,
	0xfe, 0x2b, 0xdd, 0x8f, 0x6d, 0xf5, 0x45, 0xe8, 0x7f, 0x95, 0x8e, 0xbf, 0x7d, 0x1f, 0x4d, 0x52,
	0x3d, 0x2d, 0xaf, 0xa2, 0x58, 0xe4, 0xfd, 0x3c, 0x8d, 0xa5, 0x50, 0xe2, 0x5a, 0xf7, 0x73, 0x11,
	0xf7, 0x65, 0x11, 0xf7, 0x1f, 0x48, 0xf5, 0x1d, 0xa9, 0x2b, 0xdf, 0x96, 0xff, 0xfe, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf8, 0x95, 0x73, 0x2d, 0x13, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VirtualNetworkAgentClient is the client API for VirtualNetworkAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VirtualNetworkAgentClient interface {
	Invoke(ctx context.Context, in *VirtualNetworkRequest, opts ...grpc.CallOption) (*VirtualNetworkResponse, error)
	CheckNotification(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.NotificationResponse, error)
}

type virtualNetworkAgentClient struct {
	cc *grpc.ClientConn
}

func NewVirtualNetworkAgentClient(cc *grpc.ClientConn) VirtualNetworkAgentClient {
	return &virtualNetworkAgentClient{cc}
}

func (c *virtualNetworkAgentClient) Invoke(ctx context.Context, in *VirtualNetworkRequest, opts ...grpc.CallOption) (*VirtualNetworkResponse, error) {
	out := new(VirtualNetworkResponse)
	err := c.cc.Invoke(ctx, "/moc.nodeagent.network.VirtualNetworkAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualNetworkAgentClient) CheckNotification(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.NotificationResponse, error) {
	out := new(common.NotificationResponse)
	err := c.cc.Invoke(ctx, "/moc.nodeagent.network.VirtualNetworkAgent/CheckNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualNetworkAgentServer is the server API for VirtualNetworkAgent service.
type VirtualNetworkAgentServer interface {
	Invoke(context.Context, *VirtualNetworkRequest) (*VirtualNetworkResponse, error)
	CheckNotification(context.Context, *empty.Empty) (*common.NotificationResponse, error)
}

// UnimplementedVirtualNetworkAgentServer can be embedded to have forward compatible implementations.
type UnimplementedVirtualNetworkAgentServer struct {
}

func (*UnimplementedVirtualNetworkAgentServer) Invoke(ctx context.Context, req *VirtualNetworkRequest) (*VirtualNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (*UnimplementedVirtualNetworkAgentServer) CheckNotification(ctx context.Context, req *empty.Empty) (*common.NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNotification not implemented")
}

func RegisterVirtualNetworkAgentServer(s *grpc.Server, srv VirtualNetworkAgentServer) {
	s.RegisterService(&_VirtualNetworkAgent_serviceDesc, srv)
}

func _VirtualNetworkAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualNetworkAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.nodeagent.network.VirtualNetworkAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualNetworkAgentServer).Invoke(ctx, req.(*VirtualNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualNetworkAgent_CheckNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualNetworkAgentServer).CheckNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.nodeagent.network.VirtualNetworkAgent/CheckNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualNetworkAgentServer).CheckNotification(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _VirtualNetworkAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.nodeagent.network.VirtualNetworkAgent",
	HandlerType: (*VirtualNetworkAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _VirtualNetworkAgent_Invoke_Handler,
		},
		{
			MethodName: "CheckNotification",
			Handler:    _VirtualNetworkAgent_CheckNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "virtualnetwork.proto",
}
